In [1]:
import numpy as np

In [3]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])
arr2 = np.array([
    [4,5,6],
    [7,8,9]
])

In [9]:
combined = np.array([arr1, arr2])
combined.shape

(2, 2, 3)

In [17]:
def np_concat_2d(arrs):
    row = len(arrs[0])
    return np.array([np.concatenate([a[i] for a in arrs]) for i in range(0, row)])

In [18]:
np_concat_2d(combined)

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [19]:
np.array([[1]])

array([[1]])

In [20]:
concated = np_concat_2d(combined)
concated

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [22]:
np.array_split(concated, 2)

[array([[1, 2, 3, 4, 5, 6]]), array([[4, 5, 6, 7, 8, 9]])]

In [23]:
np.split(concated, 2)

[array([[1, 2, 3, 4, 5, 6]]), array([[4, 5, 6, 7, 8, 9]])]